language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- cd code && cp src/credentials.h.sample src/credentials.h && pio run
